name: Update WeChat Rules

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 (北京时间早8点) 自动执行
  workflow_dispatch:      # 允许手动点击按钮执行
  push:
    paths:
      - 'convert.py'      # 当你修改脚本时也自动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Conversion Script
        run: python convert.py

      - name: Commit and Push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Routine Update: WeChat.yaml"
          file_pattern: 'WeChat.yaml'
